### PR TITLE
ANT-2942

### PR DESCRIPTION
**Pull request by eleon-chata-ai**
- sorting not working on pivot table

### CODE REVIEW

**Review by alexzhou-chata — COMMENTED** [review]
you didn't update the version number

**Comment by alexzhou-chata** [comment]
you have to run `npm install` in the root folder after you update the version, so that the package-lock.json will get updated with that version.

**Review by eleon-chata-ai — COMMENTED** [review]
> you didn't update the version number 

updated

**Review by eleon-chata-ai — COMMENTED** [review]
> you have to run `npm install` in the root folder after you update the version, so that the package-lock.json will get updated with that version. 

updated and pushed

**Review by alexzhou-chata — APPROVED** [review]

**Pull request merged**
